version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: cfarm-ir-app:v1
    container_name: cfarm_ir_app
    restart: unless-stopped
    working_dir: /var/www/html
    environment:
      APP_NAME: "CFARM IR System"
      APP_ENV: production
      APP_KEY: "base64:iZpDnX7tcAUX9QUJNXikuAxOSx93g94UEERNKOdJ3v4="
      APP_DEBUG: "true"
      APP_URL: "http://192.168.7.3:2019"
      LOG_CHANNEL: stderr
      DB_CONNECTION: mysql
      DB_HOST: 192.168.7.3
      DB_PORT: 3308
      DB_DATABASE: cfarm_ir
      DB_USERNAME: itadmin
      DB_PASSWORD: "Noipalee@09"
    networks:
      - cfarm_network

  webserver:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    image: cfarm-ir-webserver:v1
    container_name: cfarm_ir_webserver
    restart: unless-stopped
    ports:
      - "2019:80"
    networks:
      - cfarm_network
    depends_on:
      - app
      
  scheduler:
    image: cfarm-ir-app:v1
    container_name: cfarm_ir_scheduler
    restart: unless-stopped
    working_dir: /var/www/html
    command: php artisan schedule:work
    environment:
      APP_NAME: "CFARM IR System"
      APP_ENV: production
      APP_KEY: "base64:iZpDnX7tcAUX9QUJNXikuAxOSx93g94UEERNKOdJ3v4="
      APP_DEBUG: "true"
      APP_URL: "http://192.168.7.3:2019"
      LOG_CHANNEL: stderr
      DB_CONNECTION: mysql
      DB_HOST: 192.168.7.3
      DB_PORT: 3308
      DB_DATABASE: cfarm_ir
      DB_USERNAME: itadmin
      DB_PASSWORD: "Noipalee@09"
    networks:
      - cfarm_network
    depends_on:
      - app

networks:
  cfarm_network:
    driver: bridge
